name: Deploy Branch main
on:
  push:
    tags:
      - main-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Version
        run: |
          echo "Version: ${{ github.ref_name }}"
